
# The default Mint category.
DEFAULT_MINT_CATEGORY = 'Shopping'

# The default return category.
DEFAULT_MINT_RETURN_CATEGORY = 'Returned Purchase'

KEYWORD_TO_MINT_CATEGORY = {
    'Zipp ': 'Triathlon',
    'Nuun': 'Triathlon',
    'Cee Gees': 'Triathlon',
    'Symbiotics': 'Supplements',
    'First Endurance': 'Triathlon',
    'Honey Stinger': 'Triathlon',
    'ProLab': 'Supplements',
    'Zinc': 'Supplements',
    'Calcium': 'Supplements',
    'Nature Made': 'Supplements',
    'Optygen': 'Supplements',
    'L-Glutamine': 'Supplements',
    'Treadmill': 'Triathlon',
    'Drymax': 'Triathlon',
    'TechKewl': 'Triathlon',
    'Continental': 'Triathlon',
    'HOTSHOT': 'Triathlon',
    'LOCK LACES': 'Triathlon',
    'Shimano': 'Triathlon',
    'Specialized': 'Triathlon',
    'Rock N Roll': 'Triathlon',
    'ProGold': 'Triathlon',
    'Lizard Skins': 'Triathlon',
    'Optimum': 'Supplements',
    'Hydration': 'Triathlon',
    'CamelBak': 'Triathlon',
    'Strokemaker': 'Triathlon',
    'Vittoria': 'Triathlon',
    'Clean Bottle': 'Triathlon',
    'Speedo': 'Triathlon',
    'HEED': 'Triathlon',
    'CO2': 'Triathlon',
    'Park Tool': 'Triathlon',
    'Presta': 'Triathlon',
    'Powerbar': 'Triathlon',
    'Yankz!': 'Triathlon',
    'GU ': 'Triathlon',
    'Bonk Breaker': 'Triathlon',
    'FuelBelt': 'Triathlon',
    'SUCCEED S': 'Triathlon',
    'Profile Design': 'Triathlon',
    'Topeak': 'Triathlon',
    'Torhans': 'Triathlon',
    'Pearl Izumi': 'Triathlon',
    'Osmo ': 'Triathlon',
    'Trace Minerals': 'Triathlon',
    'Tyr ': 'Triathlon',
    'Aqua Sphere': 'Triathlon',
    'EFS ': 'Triathlon',
    'Garmin': 'Triathlon',
    'Polar Bottle': 'Triathlon',
    'SRAM': 'Triathlon',
    'FRS ': 'Supplements',
    'XLC ': 'Triathlon',
    'Skratch': 'Triathlon',
    'Smith Optics': 'Triathlon',
    'TriRig': 'Triathlon',
    'Wahoo': 'Triathlon',
    'Silca': 'Triathlon',
    'Fizik': 'Triathlon',
    'Chamois': 'Triathlon',
    'Bike': 'Triathlon',
    'Castelli': 'Triathlon',
    'CrampsAWAY': 'Triathlon',
    'Oakley': 'Triathlon',
    'Base Performance': 'Triathlon',
    'Bodyglide': 'Triathlon',
    'XLAB': 'Triathlon',
    'CycleOps': 'Triathlon',
    'Camp': 'Home',
    'Emergency': 'Home',
    'Terro': 'Home',
    'Pregnancy': 'Baby Supplies',
    'Flashlight': 'Home',
    'Batteries': 'Home',
}

# A category mapping of Amazon Order History "Categories" into Mint
# "Categories".
AMAZON_TO_MINT_CATEGORY = {
    'Accessory': DEFAULT_MINT_CATEGORY,
    'Apparel': 'Clothing',
    'Audio CD': 'Music',
    'Automotive': 'Auto & Transport',
    'Baby Product': 'Baby Supplies',
    'Blu-ray': 'Movies & DVDs',
    'CD-ROM': 'Music',
    'Camera': 'Electronics & Software',
    'Electronics': 'Electronics & Software',
    'Eyewear': 'Eyecare',
    'Grocery': 'Groceries',
    'Hardcover': 'Books',
    'Health and Beauty': 'Personal Care',
    'Home': 'Home',
    'Kitchen': DEFAULT_MINT_CATEGORY,
    'Lawn & Patio': 'Lawn & Garden',
    'Luggage': DEFAULT_MINT_CATEGORY,
    'Mass Market Paperback': 'Books',
    'Misc.': DEFAULT_MINT_CATEGORY,
    'Office Product': 'Office Supplies',
    'Paperback': 'Books',
    'Personal Computers': 'Electronics & Software',
    'Print on Demand': DEFAULT_MINT_CATEGORY,
    'Shoes': 'Clothing',
    'Software Download': 'Electronics & Software',
    'Sports': 'Sporting Goods',
    'Sports Apparel': 'Sporting Goods',
    'T-shirt': 'Clothing',
    'Tools & Hardware': 'Home',
    'Tools & Home Improvement': 'Home Improvement',
    'Toy': 'Toys',
    'Video Game': 'Electronics & Software',
    'Watch': DEFAULT_MINT_CATEGORY,
    'Wine': 'Alcohol & Bars',
    'Wireless Phone Accessory': 'Electronics & Software',
}
